# Generated by Django 5.0.6 on 2024-05-24 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_jobpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='job_title',
            new_name='user',
        ),
    ]
