# Generated by Django 5.0.6 on 2024-05-24 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_job_title_jobpost_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='user',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='username',
            new_name='usern',
        ),
    ]
