# Generated by Django 5.0.6 on 2024-05-24 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_rename_user_jobpost_position_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='usern',
            new_name='user',
        ),
    ]
