# Generated by Django 5.0.6 on 2024-05-24 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rename_usern_jobpost_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='position',
            new_name='job_title',
        ),
    ]
