# Generated by Django 5.0.6 on 2024-05-24 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_jobapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
