# Generated by Django 5.0.6 on 2024-05-24 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_delete_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('cv', models.FileField(upload_to='cv')),
                ('experince', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=254)),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.jobpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
