# Generated by Django 5.0.6 on 2024-05-25 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_jobapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
